# Generated by Django 5.0.4 on 2024-05-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folder',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
