# Generated by Django 5.0.4 on 2024-05-09 00:24

from django.db import migrations


def assign_sort_orders(apps, schema_editor):
    # 각 모델에 대한 sort_order 설정
    models_to_update = ['Category', 'Section', 'Group', 'Folder', 'Pdf']
    for model_name in models_to_update:
        Model = apps.get_model('pdfgod', model_name)
        for index, instance in enumerate(Model.objects.all().order_by('id'), start=1):
            instance.sort_order = index
            instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pdfgod', '0002_category_sort_order_folder_sort_order_and_more'),  # 이전 마이그레이션 파일 이름
    ]

    operations = [
        migrations.RunPython(assign_sort_orders),
    ]