# Generated by Django 5.0.4 on 2024-05-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgod', '0003_auto_20240509_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='is_copied',
            field=models.BooleanField(default=False),
        ),
    ]
